blend.gbuffers_basic.colortex3 = off
blend.gbuffers_hand.colortex3 = off
blend.gbuffers_hand.colortex0 = off
blend.gbuffers_hand.colortex1 = off
blend.gbuffers_hand.colortex2 = off
blend.gbuffers_textured_lit.colortex0 = off
blend.gbuffers_textured_lit.colortex1 = off
blend.gbuffers_textured_lit.colortex2 = off
blend.gbuffers_entities.colortex0 = off
blend.gbuffers_entities.colortex1 = off
blend.gbuffers_entities.colortex2 = off
blend.gbuffers_water.colortex0 = off
blend.gbuffers_water.colortex1 = off
blend.gbuffers_water.colortex2 = off
blend.gbuffers_hand_water.colortex0 = off
blend.gbuffers_hand_water.colortex1 = off
blend.gbuffers_hand_water.colortex2 = off

customTexture.vignettetex = textures/vignette.png
customTexture.stardirtex = textures/stardir.dat TEXTURE_2D RGBA16F 512 512 RGBA HALF_FLOAT
customTexture.starcoltex = textures/starcol.dat TEXTURE_2D RGBA8 512 512 RGBA UNSIGNED_BYTE

texture.noise = textures/noise.png

sliders = VIGNETTE_AMOUNT BLOOM_STRENGTH BLOOM_THRESHOLD BLOOM_KNEE BLOOM_MAX_MIPS BLOOM_DITHER

separateAo = true

sky = false
moon = false
sun = false
stars = true
clouds = false
underwaterOverlay = false

program.gbuffers_skybasic.enabled = false
program.gbuffers_skytextured.enabled = false
program.gbuffers_clouds.enabled = false
program.gbuffers_weather.enabled = false

uniform.vec3.sunDirection = vec3(gbufferModelViewInverse.0.0 * sunPosition.x * 0.01 + gbufferModelViewInverse.1.0 * sunPosition.y * 0.01 + gbufferModelViewInverse.2.0 * sunPosition.z * 0.01, gbufferModelViewInverse.0.1 * sunPosition.x * 0.01 + gbufferModelViewInverse.1.1 * sunPosition.y * 0.01 + gbufferModelViewInverse.2.1 * sunPosition.z * 0.01, gbufferModelViewInverse.0.2 * sunPosition.x * 0.01 + gbufferModelViewInverse.1.2 * sunPosition.y * 0.01 + gbufferModelViewInverse.2.2 * sunPosition.z * 0.01 )
uniform.vec3.moonDirection = vec3(gbufferModelViewInverse.0.0 * moonPosition.x * 0.01 + gbufferModelViewInverse.1.0 * moonPosition.y * 0.01 + gbufferModelViewInverse.2.0 * moonPosition.z * 0.01, gbufferModelViewInverse.0.1 * moonPosition.x * 0.01 + gbufferModelViewInverse.1.1 * moonPosition.y * 0.01 + gbufferModelViewInverse.2.1 * moonPosition.z * 0.01, gbufferModelViewInverse.0.2 * moonPosition.x * 0.01 + gbufferModelViewInverse.1.2 * moonPosition.y * 0.01 + gbufferModelViewInverse.2.2 * moonPosition.z * 0.01 )
uniform.vec3.shadowDirection = vec3(gbufferModelViewInverse.0.0 * shadowLightPosition.x * 0.01 + gbufferModelViewInverse.1.0 * shadowLightPosition.y * 0.01 + gbufferModelViewInverse.2.0 * shadowLightPosition.z * 0.01, gbufferModelViewInverse.0.1 * shadowLightPosition.x * 0.01 + gbufferModelViewInverse.1.1 * shadowLightPosition.y * 0.01 + gbufferModelViewInverse.2.1 * shadowLightPosition.z * 0.01, gbufferModelViewInverse.0.2 * shadowLightPosition.x * 0.01 + gbufferModelViewInverse.1.2 * shadowLightPosition.y * 0.01 + gbufferModelViewInverse.2.2 * shadowLightPosition.z * 0.01 )

uniform.float.fakeGIAmount = 4.0 * abs(sunDirection.y) * (1.0 - abs(sunDirection.y))
uniform.float.ambientAmount = sqrt(max(sunDirection.y, 0.0)) * 0.5 + 0.5

{{RT_SIZE}}